### ISSUE TITLE
Renaming QA

### ISSUE THREAD

**Issue by farmanp** [Ballot-Drop/ballot-drop#15]
Issue is a change request for naming QA. I understand it's not my project and this is strictly feedback I hope to make constructive for you. From what I understand, you have this component, QA. To me, QA usually means quality assurance. How you have it, it's meant to be for question and answer... I think it might be better to either separate question and answer components, OR rewrite the name here. Perhaps something along the lines of survey or write the name out QuestionAndAnswer.

**Comment by pjhoberman** [comment]
Great idea!

**Comment by scarrington76** [comment]
I'll work on this one!
