### ISSUE TITLE
some long county info 'website links' are going offscreen

### ISSUE THREAD

**Issue by nickbouldien** [Ballot-Drop/ballot-drop#43]
Can probably be fixed in `CountyInfo.vue`.  Might have to add some sort of text wrapping.

Check that it works on both small desktop screens and on the mobile/responsive simulator

EDIT: really the main problem is that it can make the google map and table not use the full screen width

![image](https://user-images.githubusercontent.com/25350512/94824955-cb0b8280-03c2-11eb-8a30-cd1b7b2009c4.png)

**Comment by ezekohon** [comment]
I think this one is already solved.
