### ISSUE TITLE
Force sentence case on data

### ISSUE THREAD

**Issue by pjhoberman** [Ballot-Drop/ballot-drop#49]
Some of the data is all caps. Let's force it to sentence case. Example: http://ballotdrop.org/North-Carolina/Alamance-County

While we can fix it in the data, with so many people submitting data, let's capture it on the front end as well.

**Comment by ezekohon** [comment]
Hi! I'd like to collaborate. Specifically which data should be sentence case? The app demo is not working for me, the dropdown is empty.

**Comment by pjhoberman** [comment]
Hi @ezekohon! Thanks for jumping in. If you want to join our slack, please feel free: https://join.slack.com/t/ballotdrop/shared_invite/zt-hdeyo1vk-VarchL5nx0ok1NpMfZh0fQ

Otherwise, I'm happy to chat through comments here. Let me know if you need anything!
