### ISSUE TITLE
create dev/staging environment on heroku, deploying from a staging branch (or similar)

### ISSUE THREAD

**Issue by nickbouldien** [Ballot-Drop/ballot-drop#75]
Create a dev/staging environment on heroku, if it doesn't cost anything (I can't remember all the details of heroku's free/hobby tier)

**Comment by pjhoberman** [comment]
It's free. I'm paying $7/mo for production just to keep it alive at all times.

**Comment by nickbouldien** [comment]
awesome.  I guess there are roughly three parts to this (can make other tickets if desired)

1. create a dev or staging branch (from master)
2. create the staging environment on heroku
3. create the pipeline (similar to what exists for master->prod) to deploy on the staging env when the a branch is merged to the staging branch

**Comment by pjhoberman** [comment]
Done. http://staging.ballotdrop.org/

When you open a PR, you'll have to pick staging instead of master as the branch, or I can change github to default to staging as the main branch.

**Comment by pjhoberman** [comment]
I connected staging to the staging env on heroku, so when you merge into staging (or push staging from your local, as it's not protected), it will trigger a build, and also spit out info on slack
