### ISSUE TITLE
force https

### ISSUE THREAD

**Issue by nickbouldien** [Ballot-Drop/ballot-drop#78]
looks like you can get to http://ballotdrop.org/ if you just type in `ballotdrop.org/`.  We probably want to force https

![image](https://user-images.githubusercontent.com/25350512/95489930-ba27b780-0954-11eb-84ec-a2ec9e1f11f3.png)

https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls ??

**Comment by pjhoberman** [comment]
Turns out this is a bit tricky since we're basically a static site (no real node or express code going on). one thought is that I can drop our cert. We're not collecting data... thoughts?

**Comment by sreynen** [comment]
Maybe we could just do a redirect on the front end? I'm not familiar enough with Vue to know where this would go, but I imagine we could drop `if (location.protocol !== 'https:') { location.href = ...}` somewhere. Browsers throw up enough scary messages about HTTP now that it's probably worth avoiding if possible even if there's no actual security concern.

**Comment by nickbouldien** [comment]
yea, I was thinking it might get tricky since it's a static site, but I guess I assumed Heroku would have some type of solution.  

not sure where you registered the domain, but could we try to redirect there? something like this?? not sure of all the details since I didn't register the domain or create and setup the project on heroku

 https://stackoverflow.com/questions/46923055/how-do-you-force-https-with-namecheap-and-heroku

**Comment by pjhoberman** [comment]
DNS is an area that I always feel like I'm going to screw up.

But, I just launched a staging env, so let's try the vanilla js answer first.. unless that will wreck SEO or anything like that (though I don't think it will) 

#75

**Comment by pjhoberman** [comment]
Also, @nickbouldien it's registered with name.com
